spring:
  application:
    name: openremote-crud

openremote:
  url: ${OPENREMOTE_URL:https://openremote.example.com}
  client-id: ${OPENREMOTE_CLIENT_ID:serviceuser}
  client-secret: ${OPENREMOTE_CLIENT_SECRET:secret}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    filter: true
